name: transformers-cpu
channels:
  - huggingface
  - pytorch
  - nvidia
dependencies:
  - python=3.8
  - pip
  - yapf>=0.30
  - ipykernel>=6.9.1
  - pandas>=1.4.1
  - pytorch=1.11
  - torchvision=0.12
  - torchaudio=0.11
  - cpuonly=2.0
  - tensorflow=2.4.1
  - transformers=4.11
  - pip:
      - aitextgen==0.5.2
